name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deployment
    runs-on: ubuntu-latest

    steps:
      - name: get the source code
        uses: action/checkout@v2

      - name: install node
        uses: action/setup-node@v2
        with:
          node-version: "14"

      - name: install node packages
        run: npm i

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
